### ISSUE TITLE
Uploading a photo causes the next photo upload to be undefined

### ISSUE THREAD

**Issue by vu035** [Darkorin/commongg#100]
Steps to Reproduce: 

1. Navigate to settings page within app
2. Pick a new photo
3. click Update
4. Observe upload -- notice the profile photo within nav bar becomes undefined
5. Select same photo
6. Select update again
7. Photo uploads and displays in profile bar without being undefined

**Comment by CarrotWiz** [comment]
You don't have to be uploading a new photo. Navigating to the settings page and pressing the upload button will immediately make the photo undefined.

**Comment by vu035** [comment]
Good solution I like this keep up the hustle @seanyang0813 and good find @CarrotWiz
