### ISSUE TITLE
new account bugs out without games

### ISSUE THREAD

**Issue by seanyang0813** [Darkorin/commongg#104]
I am guessing it's nav bar 

  50 | <Link to="/trending" style={linkStyle}>
  51 |     <p><img src={trend} style={iconStyle} alt="" /> trending</p>
  52 | </Link>
> 53 | <Link to="/settings" style={linkStyle}>
     | ^  54 |     <p><img src={setting} style={iconStyle} alt="" /> settings</p>
  55 | </Link>
  56 | {props.currentUserInfo.games.map((game) => {

**Comment by seanyang0813** [comment]
only seems to be an issue when doing things locally sign up on alpha seems to be ok

**Comment by vu035** [comment]
I think this is only possible if you remove all the games in the DB but it appears to be defaulting to "Common Chat"
