### ISSUE TITLE
Need to display common logo in place of profile picture when undefined

### ISSUE THREAD

**Issue by vu035** [Darkorin/commongg#113]
Need to display common logo in place of profile picture when undefined

**Comment by seanyang0813** [comment]
Is there still a way to make the image undefined? The only way I can think of when you upload the wrong type but in that case the db is not returning nothing I think it's just returning something we can't display

**Comment by vu035** [comment]
Yeah. Maybe a little bit more clarity on the issue would be good, too. But basically, scenarios where the profile picture might show that little weird white space instead of an actual image. in DEV environment, though, you would just delete the profile_picture property for the json object in the db would make the profile_picture undefined. Just make sure you're deleting the one you're using for testing though ;)

**Comment by vu035** [comment]
Bump -- this is also reported by beta testers
